<?= $this->doctype('HTML5') ?>
<html lang="pt-br">
<head>
	<meta charset="utf-8" />
	<meta name="description" content="Mini Blog em Zend" />
	<base href="http://<?=$_SERVER['HTTP_HOST'] . $this->baseUrl()?>/" />
	<title>Mini Blog em Zend</title>
	
	<link rel="stylesheet" href="css/stylesheet.css" type="text/css" media="screen" />
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="media/js/jquery-1.7.2.min.js"><\/script>')</script>
	
	<!--[if IE]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
	<!--[if lt IE 7 ]>
		<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
		<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
	<![endif]-->
</head>
<body>

<div id="todo">

	<div id="header">
		<header>
			<h1><a href="<?= $this->url(array("controller" => "index", "action" => "index"), null, true) ?>" title="Blog">Blog...</a></h1>
		</header>
	</div>

	<div id="menu">
		<nav>
			<ul>
				<li><a href="<?= $this->url(array("controller" => "index", "action" => "index"), null, true) ?>" title="Página Inicial">HOME</a></li>
				<li><a href="<?= $this->url(array("controller" => "index", "action" => "sobre"), null, true) ?>" title="Sobre o blog">SOBRE</a></li>
				<li><a href="<?= $this->url(array("controller" => "post", "action" => "index"), null, true)  ?>" title="CRUD">CRUD POSTAGENS</a></li>
			</ul>
		</nav>
	</div>

	<?php echo $this->layout()->content; ?>	

</div>

</body>
</html>
