
<div id="postagens">

<p class="cabecalho">listar posts</p>

<table cellspacing="0" cellpadding="0">
	 <thead><th>nº</th> <th class="titulo">titulo</th> <th>cadastro</th> <th>ações</th></thead>
	 <tbody>
	 		<tr>
		 		<td>32</td>
		 		<td class="titulo">Alguma coisa</td>
		 		<td>36/08/2012</td>
		 		<td>
		 			<a href="" class="novo" title="novo post">novo -</a>
		 			<a href="" class="editar post" title="editar">editar -</a>
		 			<a href="" class="deletar post" title="deletar">deletar</a>
		 		</td>
		 	</tr>

	 </tbody>
</table>

</div>